#!/bin/bash
set -e

# ----------------------------------------------------------------------------
# Pastikan folder writable & uploads ada (jika di-mount sebagai volume kosong)
# ----------------------------------------------------------------------------
mkdir -p \
    /var/www/html/writable/cache \
    /var/www/html/writable/logs \
    /var/www/html/writable/session \
    /var/www/html/writable/uploads \
    /var/www/html/writable/debugbar \
    /var/www/html/uploads

# Fix permission setiap container start (volume seringkali milik root)
chown -R www-data:www-data \
    /var/www/html/writable \
    /var/www/html/uploads 2>/dev/null || true

chmod -R 775 \
    /var/www/html/writable \
    /var/www/html/uploads 2>/dev/null || true

# ----------------------------------------------------------------------------
# Generate .env CodeIgniter4 dari environment variables Docker.
# Ini lebih reliable daripada pass env dengan format "app.baseURL=..." karena
# Docker Compose substitution dan PHP getenv() kurang konsisten dengan
# nama variable yang mengandung titik.
# ----------------------------------------------------------------------------
cat > /var/www/html/.env <<EOF
#--------------------------------------------------------------------
# Generated by entrypoint.sh — JANGAN edit manual di container.
# Ubah env vars di panel Coolify, lalu redeploy.
#--------------------------------------------------------------------

CI_ENVIRONMENT = ${CI_ENVIRONMENT:-production}

app.baseURL = '${APP_BASE_URL:-http://localhost/}'
app.forceGlobalSecureRequests = ${FORCE_HTTPS:-false}
app.indexPage = ''

database.default.hostname = ${DB_HOST:-mariadb}
database.default.database = ${DB_DATABASE:-db_letter}
database.default.username = ${DB_USERNAME:-letter_user}
database.default.password = ${DB_PASSWORD}
database.default.DBDriver  = MySQLi
database.default.port      = ${DB_PORT:-3306}
database.default.charset   = utf8mb4
database.default.DBCollat  = utf8mb4_general_ci

encryption.key = ${ENCRYPTION_KEY:-}
EOF

chown www-data:www-data /var/www/html/.env
chmod 640 /var/www/html/.env

echo "[entrypoint] .env generated. baseURL=${APP_BASE_URL:-<unset>}"

exec "$@"
